seed: 888
data: data/
processed: data/output/
dataset:
  base: data/base/
  clss: ['aa', 'ag', 'bc', 'dd', 'fd', 'ff', 'hd', 'ns', 'ta', 'tc']
  splits: 3
  repeats: 2
  s_per_class: 300
train:
  data_dir: data/output/0_split/
  train_dir: aug
  val_dir: val
  im_size: 256
  batch_size: 16
  epochs: 1
  model: models.resnet152